CROSS_COMPILE = aarch64-linux-gnu-
CXX=$(CROSS_COMPILE)g++
CXXFLAGS = -std=c++11
OBJ=circular_sector.o ellipse.o sort.o triangle.o main.o
SRC=circular_sector.cpp ellipse.cpp sort.cpp triangle.cpp main.cpp
EXE=main
LIBS= -lm

all:$(EXE)
$(EXE):$(OBJ)
	$(CXX) $(CXXFLAGS) -o $@ $? $(LIBS)

.PHONY:clean
clean:
	rm -rf $(OBJ) $(EXE)
